### DISCUSSION TITLE
Using action to deploy to staging/preview url and working directory should be `build` or `root` dir

### DISCUSSION THREAD

**Discussion by Pranav016** [amondnet/vercel-action#142] [Q&A]
```
name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./sub-directory
```

If I remove the `vercel-args: --prod` input from the action then would it deploy to staging? Because that's what happens when we run `vercel` command locally without the `--prod` flag.
I want to deploy my PRs to staging/ a preview url before merging which I'll deploy to production.

Also, I am working on a react app thus the `working-directory` input will be my build folder(`./build`) right ? That I want to deploy or will it be the root dir of my project?
