### DISCUSSION TITLE
Question: How to use build time environment variables with `vercel deploy --prebuilt`

### DISCUSSION THREAD

**Discussion by dgokcin** [amondnet/vercel-action#191] [Q&A]
Hello!

I am using GitHub actions to build my next.js app and deploy from GitHub Actions with the --pre-built argument. What do you recommend if I want to have both build time and run time environment variables? And for sensitive variables like API Keys, I initially thought of the GitHub Actions Secrets but I could not figure out a way to combine them with environment specific env files. I am attaching my workflow below, any suggestion is appreciated :)

Thanks
```

name: Deploy to Vercel from Strapi Webhook
on:
  repository_dispatch:
    types: deploy_to_qa

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_GHA_TOKEN }}
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
  NODE_VERSION: 16.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.target_branch }}
          fetch-depth: 0
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Print The branch name from the webhook
        run: echo ${{ github.event.client_payload.target_branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Pull Project Settings from Vercel
        run: yarn vercel pull --yes --environment=development --token=${{ env.VERCEL_TOKEN }}

      - name: Vercel Build
        run: yarn vercel build

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: --prebuilt #Optional
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID}} #Required
          scope: ${{ env.VERCEL_TEAM_ID }} #Optional
          alias-domains: | 
           example.com
```
