### DISCUSSION TITLE
Comments on PR when using push-triggered workflows

### DISCUSSION THREAD

**Discussion by markoleavy** [amondnet/vercel-action#260] [Q&A]
All of my workflows are push-triggered. It's seems the action looks for a previous comment in the PR, but not founding it, it doesn't produce a new one. Here's part of my main workflow config:
```yml
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - production
      - preprod
      - 'feature/**'

# permission can be added at job level or workflow level
permissions:
  id-token: write
  contents: write
  pull-requests: write
  deployments: write
jobs:
  build-stack-and-deploy:
    runs-on: ubuntu-22.04
    name: Build stack and deploy
    timeout-minutes: 60
    steps:
        - OTHER STEPS
        - name: Deploy CMS
           id: deploy-cms
           uses: amondnet/vercel-action@v25
           with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            github-comment: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
            vercel-project-id: ${{ vars.VERCEL_CMS_PROJECT_ID }}
            vercel-org-id: ${{ vars.VERCEL_TEAM_ID }}

```
And here's the last part of the log:
```log
set preview-name output
this is push event
find comment
previous comment not found
```
Is there a way to force PR comment creation? Commit comments work properly.
