### ISSUE TITLE
Vercel Deployment fails due to "missing input"

### ISSUE THREAD

**Issue by Jarmos-san** [amondnet/vercel-action#105]
Thanks for the great work!

And this issue might as well be related to #26. The only diff though this issue isn't related to Dependabot PRs.

Expected behaviour is for this Action to deploy on each push-event (if configured as such). But it crashes for my project every time with the following error:

```console
Run amondnet/vercel-action@v20
  with:
    vercel-args: --prod
    github-comment: true
    github-deployment: false
/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:2205
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: vercel-token
    at Object.getInput (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:2205:15)
    at Object.679 (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:24158:26)
    at __webpack_require__ (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:37:19)
    at /home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```
And I'm pretty sure the GitHub Secrets are configured correctly. Screenshot attached for reference:
![image](https://user-images.githubusercontent.com/31373860/131997370-39d6fcb3-6439-471d-9ceb-ae1c38b5d6c8.png)

For more reference on how I configured the Action, here's a code snippet:

```yaml
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
```

What am I missing out on for it to crash that way? Or is there something else wrong here?

Do let me know if you need more information.
