### ISSUE TITLE
Error: SHA1 sum of the file (...) doesn't match the provided SHA1 sum (...)

### ISSUE THREAD

**Issue by aalzanki** [amondnet/vercel-action#116]
We are intermittently getting the following error when we deploy using the Github action:
```
Error! SHA1 sum of the file (dbf530c4b45143fee366731ef310231595032f37) doesn't match the provided SHA1 sum (df2570531e9643f1745bc8b4903b711117c1eb71)

Error! SHA1 sum of the file (dbf530c4b45143fee366731ef310231595032f37) doesn't match the provided SHA1 sum (df2570531e9643f1745bc8b4903b711117c1eb71)

Error: The process '/opt/hostedtoolcache/node/14.19.0/x64/bin/npx' failed with exit code 1
``` 

The error often goes away by retrying the action, but the error has been occuring probably around 30% of the time that the action runs. It's happening on both preview and production deploys.

Here's an example of how we are running the action:
```
- uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
                  github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
                  scope: ${{ secrets.ORG_ID}} #Required
                  vercel-org-id: ${{ secrets.ORG_ID}} #Required
                  vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
                  vercel-args: '--prod' #Optional
                  github-comment: false
                  working-directory: ./
```

I tried to find information online about this error, but couldn't really find anything. Does anyone know why this is happening?

We have some code that could be creating some temp files while the action is running. Could this be the cause of the issue? Any information on this would be very helpful. Thank you all!
