### ISSUE TITLE
How to re-authenticate

### ISSUE THREAD

**Issue by peterkimzz** [amondnet/vercel-action#138]
My action is stuck when this action is triggered.

Here is my snippet.
```yaml
- name: Vercel
   uses: amondnet/vercel-action@v20
   id: vercel
   with:
      vercel-token: TOKEN
      vercel-org-id: ORG_ID
      vercel-project-id: PROJECT_ID
``` 

And wait for it forever.
```bash
Retrieving project…
> You must re-authenticate to use brianalabs scope.

> You must re-authenticate to use brianalabs scope.
> Log in to Vercel (Use arrow keys)
❯ Continue with GitHub 
  Continue with GitLab 
  Continue with Bitbucket 
  Continue with Email 
  ───────────────────────
  Abort 
> Log in to Vercel (Use arrow keys)
❯ Continue with GitHub 
  Continue with GitLab 
  Continue with Bitbucket 
  Continue with Email 
  ───────────────────────
  Abort 
```

**Comment by amondnet** [comment]
@peterkimzz 
1. Does vercel token have permission in team scope?
2. Did you disable vercel build?  
  - https://github.com/amondnet/vercel-action#disable-vercel-for-github
  - https://github.com/amondnet/vercel-action#skip-vercels-build-step

**Comment by peterkimzz** [comment]
Hi, @amondnet 

Yes, it has a team scope. Actually, I found the solution a few days ago.
Thank you!

```yaml
- name: Vercel
   uses: amondnet/vercel-action@v20
   id: vercel
   with:
      vercel-token: TOKEN
      vercel-org-id: ORG_ID
      vercel-project-id: PROJECT_ID
      scope: TEAM_SLUG
```
