### ISSUE TITLE
Deployment returns 404 page

### ISSUE THREAD

**Issue by AshNaz87** [amondnet/vercel-action#140]
Hi @amondnet!

You have an amazing tool! Thank you for making this public.

I'm having issues getting my repo to deploy correctly. I have a feeling there is an issue with the build.

The repo itself is a Next.js app using TypeScript. I believe the build assets lie in the `.next` directory, but perhaps you can point me in the right direction.

Many thanks :)

**Comment by amondnet** [comment]
```yaml
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: .next
```
@AshNaz87  Use `working-directory: .next` or `vercel-args: .next`. Please let me know if this doesn't work
