### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by sweepy84** [amondnet/vercel-action#148]
For some reason im getting this error "Resource not accessible by integration" which fails the action.

> Creating alias
>  Success! https://mydomain.io/ now points to https://mydomain.vercel.app/ [992ms]
> this is related issue or pull_request
> find comment
> Error: Resource not accessible by integration

My configuration:
```
name: Deploy ui preview
uses: amondnet/vercel-action@v20
id: vercel-action-staging
if: github.event_name == 'pull_request'
with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  vercel-token: ${{ secrets.VERCEL_TOKEN }}
  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  scope: ${{ secrets.VERCEL_ORG_ID}}
  alias-domains: |
    mydomain.io
```
