### ISSUE TITLE
There was an error when attempting to execute the process

### ISSUE THREAD

**Issue by morganfeeney** [amondnet/vercel-action#16]
Hi, I'm attempting to use vercel-action but keep running into issues.

I have followed the documentation here: https://github.com/marketplace/actions/vercel-action

The latest error is this one:
![image](https://user-images.githubusercontent.com/1900222/86097639-de9a0b00-baac-11ea-845d-67261379a3eb.png)

Here's my .yml file for github actions:

```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SPACE_ID: ${{ secrets.SPACE_ID }}
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:unit

    - name: Vercel Action
      uses: amondnet/vercel-action@v19.0.1+1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
```

I'm kind of new to this, but what I'm attempting to do here is have an action run through building and testing the app, then I'd like to deploy to vercel, once tests have passed.
