### ISSUE TITLE
Alias domain - Error! You don't have access to the domain platform.example.com under team-shared.

### ISSUE THREAD

**Issue by xcfw** [amondnet/vercel-action#167]
<details><summary>When this action runs:</summary>
<p>

#### deployment.yml
```yaml
name: Vercel Deployment
on:
  push:
    branches: [ 'staging' ]

env:
  FONTAWESOME_NPM_AUTH_TOKEN: some-token
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build w node@16
        uses: actions/setup-node@v3
        with:
          node-version: '14.19.3'
          # cache: 'npm'
          # cache-dependency-path: package-lock.json
      - run: |
          npm ci
          npm run build

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN}}
          # vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          scope: team-shared
          working-directory: ./
          alias-domains: |
            platform.example.com
```
</p>
</details>

On the domain assigning step
```sh
> npx vercel -t *** --scope powr-shared alias https://platform-staging-fdlk83hsa-team-shared.vercel.app/ platform.example.com
```

Build fails and the output looks like this:

```log
Vercel CLI 25.1.0
> Assigning alias platform.example.com to deployment platform-staging-fdlk83hsa-team-shared.vercel.app
Fetching domain platform.example.com under team-shared
Error! You don't have access to the domain platform.example.com under team-shared.
Error: The process '/opt/hostedtoolcache/node/14.19.3/x64/bin/npx' failed with exit code 1
```
