### ISSUE TITLE
vercel deployment not picking up `.vercel/output/config.json`

### ISSUE THREAD

**Issue by mesqueeb** [amondnet/vercel-action#186]
@amondnet 
Since we switched to building inside the github action, it seems that `.vercel/output/config.json` is not picked up by vercel anymore.

If we add a custom `vercel.json` file it will be picked up by vercel but we're not able to properly set up our edge middleware with this file.

Is it possible to not add any `vercel.json` file to our working directory, and still have your github action send the `.vercel/output/config.json` to vercel to make sure vercel uses that information?

**Question:**<br />
Do we _need_ to add `vercel.json` ? and if so, how to do so in a way it won't clash with what we have at `.vercel/output/config.json`?

--

perhaps related: @paulrberg #123

--

extra information:
this is our `.vercel/output/config.json`
```json
{
  "version": 3,
  "routes": [
    {
      "src": "/assets/(.+)",
      "headers": { "cache-control": "public, immutable, max-age=31536000" }
    },
    { "handle": "filesystem" },
    { "src": "/(.*)", "middlewarePath": "main", "continue": true },
    { "src": "^(?:/(.*))$", "headers": { "Location": "/index.html" }, "status": 308 }
  ]
}
```

this is our folder structure
![image](https://user-images.githubusercontent.com/3253920/195785871-a4f9d89a-8ddb-4495-9cbf-44c2c95c5ccb.jpeg)

it seems that `.vercel/output/static` holds the same files as the `dist` folder... 🤔 

this is the deploy step of our github action
```yaml
      - name: Deploy App to `preview` environment
        if: needs.setup.outputs.target-environment == 'beta'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APP }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: packages/app
      - name: Deploy App to `production` environment
        if: needs.setup.outputs.target-environment == 'production'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APP }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: packages/app
```
