### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by aulneau** [amondnet/vercel-action#19]
Hi there!

I see the changes have been made for the comments bug, but there has not been a release yet. Would it be possible for you to release the new version?

Best
t

**Comment by amondnet** [comment]
I think it will be within 1~2 days. 
If you want to use the latest version, try the following. `amondnet/vercel-action@master`

```yaml
name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./sub-directory
```
