### ISSUE TITLE
Using the `alias-domains` option results in error

### ISSUE THREAD

**Issue by marcofugaro** [amondnet/vercel-action#203]
This is my deploy step:

```yml
- name: Deploy to Vercel
  uses: amondnet/vercel-action@v25
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
    vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    scope: ${{ secrets.VERCEL_ORG_SLUG }}
    github-token: ${{ secrets.GITHUB_TOKEN }}
    vercel-args: 'deploy ./apps/my-app/dist/'
    alias-domains: {{BRANCH}}.${{ secrets.VERCEL_PROJECT_URL }}
```

However, the alias command apparently is called too soon:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/7217420/206709923-b4789fb4-ce0d-4699-8a19-8e0a3287b6f6.png">

How can I alias after deploying?
