### ISSUE TITLE
Not deploying to production

### ISSUE THREAD

**Issue by jpangelle** [amondnet/vercel-action#22]
I am having trouble deploying to production. If I remove the `vercel-args: '--prod'` line, it properly deploys to my Vercel `staging` environment, but having the `vercel-args: '--prod'` line just does not deploy at all. I can not figure out why.

My `deploy-to-production.yml` config:

```yml
name: Deploy to Vercel

on:
  push:
    branches: [master]
    paths-ignore:
      - "server/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: client
  deploy-to-production:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          github-comment: false
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
```

**Comment by jpangelle** [comment]
It appears that when I run `vercel --prod` command in the terminal does nothing so maybe this is not related to this Action.

**Comment by jpangelle** [comment]
In order for it to work, I had to remove this from my `vercel.json`:
```json
{
  "github": {
    "enabled": false
  }
}```

This is still confusing me as the instructions direct you to add this. 🤷‍♂️

**Comment by jpangelle** [comment]
Actually, argggg. Still not working even with that removed.

**Comment by amondnet** [comment]
Where is your publish directory? Is it a static site? 

example
```yaml

// Your Build Script(if not static site)

      - uses: amondnet/vercel-action@v19
        with:
          github-comment: false
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: 'client' // your directory

```
