### ISSUE TITLE
env-vars with spaces fail when passed using `--env` in `vercel-args`

### ISSUE THREAD

**Issue by wilsonpage** [amondnet/vercel-action#236]
1. Set a repo secret that includes spaces (eg `-----BEGIN PRIVATE KEY----- …`)
2. Reference it in the Github Actions Workflow.

```yml
- uses: amondnet/vercel-action@v25
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    …
    vercel-args: >-
      --env MY_VAR=${{ secrets.VAR_WITH_SPACES }}
```

3. Observe bash error: `Error! The specified file or directory "PRIVATE" does not exist.`

Wrapping with `"` still fails, so I'm assuming this is an issue in vercel-action.

```yml
- uses: amondnet/vercel-action@v25
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    …
    vercel-args: >-
      --env MY_VAR="${{ secrets.VAR_WITH_SPACES }}"
```

**Comment by skyf0l** [comment]
Fixed by #237 and merged. Until the release you can use a commit pin as follows in your workflow:
```yaml
- uses: amondnet/vercel-action@8433ae13f35aa62d68184a8fc369ce6b0143b0a3
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    …
    vercel-args: >-
      --env MY_VAR="${{ secrets.VAR_WITH_SPACES }}"
```
