### ISSUE TITLE
Alias-domains multiple

### ISSUE THREAD

**Issue by jinglestaging** [amondnet/vercel-action#251]
Hello, I have
```
      - name: Deploy to Vercel App Social
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: "${{ github.ref == 'refs/heads/main' && 'www.example1.com' || '' }}"

      - name: Deploy to Vercel App Hosted
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: "${{ github.ref == 'refs/heads/main' && 'www.example2.com' || '' }}"
```
how to alias the domains www.example1.com and www.example2.com in one line? This is not working
`alias-domains: "${{ github.ref == 'refs/heads/main' && 'www.example1.com' || 'www.example2.com' }}"`

Thx
