### ISSUE TITLE
error when run action

### ISSUE THREAD

**Issue by mitraecp** [amondnet/vercel-action#253]
![image](https://github.com/amondnet/vercel-action/assets/75841640/cb2f067c-031c-427d-8cf9-f35aaa8f3d42)

anyone can help me?

i got this error when try run action

this is my yaml file

```
name: deploy
on:
  pull_request:
    branches:
      - qa
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Install Dependencies
      run: npm install

    - name: Build for Production
      run: npm run prod-build
    - uses: amondnet/vercel-action@v20 
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} 
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        vercel-org-id: ${{ secrets.ORG_ID}}  
        vercel-project-id: ${{ secrets.PROJECT_ID}} 
        working-directory: ./sub-directory
```
