### ISSUE TITLE
Input required and not supplied: `${name}`

### ISSUE THREAD

**Issue by Rawnly** [amondnet/vercel-action#26]
Hi I'm getting this error, but I've added all the tokens to the repo settings.

<img width="549" alt="immagine" src="https://user-images.githubusercontent.com/16429579/89390609-40324280-d707-11ea-9f58-c8c468920bbe.png">

<img width="662" alt="immagine" src="https://user-images.githubusercontent.com/16429579/89390645-4fb18b80-d707-11ea-9716-353b6dd35130.png">

**Comment by amondnet** [comment]
Do you still have problems? 
Try again without `name`?

**Comment by amondnet** [comment]
https://github.com/amondnet/vercel-action/runs/980730794?check_suite_focus=true

**Comment by amondnet** [comment]
```
##[warning]Input 'zeit-token' has been deprecated with message: Zeit is now Vercel. Use "vercel-token" instead
##[warning]Input 'now-org-id' has been deprecated with message: Zeit is now Vercel. Use "vercel-org-id" instead.
##[warning]Input 'now-project-id' has been deprecated with message: Zeit is now Vercel. Use "vercel-project-id" instead.
##[warning]Unexpected input(s) 'name', valid inputs are ['vercel-token', 'vercel-args', 'github-comment', 'github-token', 'github-deployment', 'working-directory', 'vercel-project-id', 'vercel-org-id', 'vercel-project-name', 'scope', 'zeit-token', 'now-args', 'now-project-id', 'now-org-id', 'alias-domains']
```

**Comment by sk-** [comment]
@amondnet we are getting these errors in PRs created by dependabot, other PRs are deployed successfully.

```
/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:2205
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: vercel-token
    at Object.getInput (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:2205:15)
    at Object.679 (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:24158:26)
    at __webpack_require__ (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:37:19)
    at /home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/amondnet/vercel-action/v20/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

Our deployment step is set up as follows:

```yaml
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          vercel-args: "--confirm"
        id: "vercel_deploy"
```
