### ISSUE TITLE
Successfully deployed but still asked for re-authenticate

### ISSUE THREAD

**Issue by qixing-jk** [amondnet/vercel-action#265]
With the following configuration, everything can be deployed normally through CI but will be asked to re-authenticate later, causing the subsequent process to fail
```
      - name: Vercel Action
        id: vercel_action
        env:
          VERCEL_ARGS: ${{ github.ref == 'refs/heads/heo' && '--prod'|| '' }}
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-args: ${{ env.VERCEL_ARGS }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          alias-domains: ${{ secrets.PROJECT_NAME}}-git-{{ BRANCH }}-${{ secrets.TEAM_NAME}}.vercel.app
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_SCOPE }}
```
GitHub Actions Log
```
Deploying small-qihang-hot/***
Deploying small-qihang-hot/***
Inspect: https://vercel.com/***/***/BiUdHZfrm5GzN9nsUsuPajB4nTYA [3s]
Inspect: https://vercel.com/***/***/BiUdHZfrm5GzN9nsUsuPajB4nTYA [3s]
Queued
Queued
https://***-n9zsq3oct-***.vercel.app
https://***-n9zsq3oct-***.vercel.appBuilding
Building
Completing
Completing
> You must re-authenticate to use small-qihang-hot scope.
> You must re-authenticate to use small-qihang-hot scope.
> Log in to Vercel (Use arrow keys)
❯ Continue with GitHub 
  Continue with GitLab 
  Continue with Bitbucket 
  Continue with Email 
  ───────────────────────
  Abort 
> Log in to Vercel (Use arrow keys)
❯ Continue with GitHub 
  Continue with GitLab 
  Continue with Bitbucket 
  Continue with Email 
  ───────────────────────
  Abort 
```
