### ISSUE TITLE
Deployment fails due to empty `githubCommitRef`

### ISSUE THREAD

**Issue by joonashak** [amondnet/vercel-action#46]
I have a workflow set up to deploy to staging on `main` branch push and and to production on release. With no changes to the workflow or env vars, the deployment to production started failing today due to an empty value for `githubCommitRef`:

![Screenshot 2020-10-24 at 18 02 15](https://user-images.githubusercontent.com/18666321/97084973-0e07f100-1623-11eb-98cf-d561cb3835bf.png)

Deployment to staging still works as it has a correct value of `refs/heads/main` for `githubCommitRef`. My previous successful deployment to production was 10 days ago and it had a value of `refs/tags/0.0.15`.

The failing workflow:

```
name: Production Deployment (Release)

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy CMS to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          appdir: cms
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PRODUCTION_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Deploy Frontend to Vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          alias-domains: |
            reclab-web.vercel.app
          working-directory: ./web
```

And the whole repository in question is available here: https://github.com/joonashak/reclab

To my knowledge, I have not changed anything that could have broken this. I tried to take a look at `vercel-action` codebase but could not figure out if the problem is with this action or my code, and thought that this would be the logical place to start asking questions.
