### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by richardtapendium** [amondnet/vercel-action#51]
When running this action, I am getting the following error:

```
/usr/local/bin/npx vercel --prod -t *** -m githubCommitSha=9c1a00cc9e604db43d6e0598ad26510a70c40f98 -m githubCommitAuthorName=richardtapendium -m githubCommitAuthorLogin=richardtapendium -m githubDeployment=1 -m githubOrg=tapendium -m githubRepo=tapendium-pwa -m githubCommitOrg=tapendium -m githubCommitRepo=tapendium-pwa -m githubCommitMessage=test -m githubCommitRef=refs/heads/vercel-deploy --scope ***

Error: There was an error when attempting to execute the process '/usr/local/bin/npx'. This may indicate the process failed to start. Error: spawn /usr/local/bin/npx ENOENT
```

My script looks like this:

```
name: deploy website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GH_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required 
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          working-directory: ./sub-directory
```

Any help is much appreciated.
