### ISSUE TITLE
feat: alias domain to deployment

### ISSUE THREAD

**Issue by amondnet** [amondnet/vercel-action#7]
## branch based
  master -> production -> `prod.vercel.amond.net`
  develop -> staging -> `staging.vercel.amond.net`

## pr number based
  PR-1 -> `pr-1.vercel.amond.net`
  PR-2 -> `pr-2.vercel.amond.net`

**Comment by amondnet** [comment]
New input variable : alias-domains

## Example

```yaml
name: example - angular
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: build
        run: |
          cd example/angular
          npm ci
          npx ng build --prod
      - uses: ./
        id: vercel-action-staging
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_ANGULAR }}
          working-directory: example/angular/dist/angular
          alias-domains: |
            staging.angular.vercel-action.amond.dev
            pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
      - uses: ./
        id: vercel-action-production
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_ANGULAR }}
          working-directory: example/angular/dist/angular
          vercel-args: '--prod '
```

You can use pull request number via `{{PR_NUMBER}}`. 
ex: `https://pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev` => https://pr-18.angular.vercel-action.amond.dev
