### ISSUE TITLE
Github action periodically times out when succeeding in Vercel (Error: The operation was canceled.)

### ISSUE THREAD

**Issue by jamesopti** [amondnet/vercel-action#98]
Were seeing our deploys periodically timeout in Github, but succeed in vercel. As a result, the deployment version for our staging or production app is not updated.

Any ideas what could be going on here? We have the timeout set for 20min, but Vercel says the deploy is only taking about 7min.

**_OUTPUT_**

```
set environment for vercel cli
set env variable : VERCEL_ORG_ID
set env variable : VERCEL_PROJECT_ID
using scope
/usr/local/bin/npx vercel --prod -t *** -m githubCommitSha=82dc9ff7a6619ebcf360b944361ceed49b919483 -m githubCommitAuthorName=jamesopti -m githubCommitAuthorLogin=jamesopti -m githubDeployment=1 -m githubOrg=acme-co -m githubRepo=acme-co -m githubCommitOrg=acme-co -m githubCommitRepo=acme-co -m githubCommitMessage=Merge pull request #591 from acme-co/main

Release 7-16-9am -m githubCommitRef=refs/heads/prod --scope ***
Vercel CLI 23.0.1

Vercel CLI 23.0.1
- Deploying acme-co/frontend-app

- Deploying acme-co/frontend-app

Inspect: https://vercel.com/acme-co/frontend-app/AYZE8qkZCkz7L3yM4mwCaRe49y9Z [16s]

Inspect: https://vercel.com/acme-co/frontend-app/AYZE8qkZCkz7L3yM4mwCaRe49y9Z [16s]
https://frontend-app-59av63uj7-acme-co.vercel.app
https://frontend-app-59av63uj7-acme-co.vercel.app- Queued

- Queued
Error: The operation was canceled.
```

**_GITHUB ACTION CONFIG_**

```
      # Deploy production app
      # See https://github.com/marketplace/actions/vercel-action
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional - Github sets this for us
          github-comment: false # Dont comment on the deploy
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          vercel-args: ${{ steps.build-args.outputs.vercel-args }}
          alias-domains: ${{ steps.build-args.outputs.alias-domain }}
```
